//! DDL generation: the exact text, both dialects, and determinism.

use cratefield_tables::{ErrorCode, Schema, SqlDialect, json_schema, validate_row};
use serde::Deserialize;
use serde_json::json;

#[derive(Deserialize)]
struct Manifest {
    tables: Schema,
}

fn schema(fragment: &str) -> Schema {
    toml::from_str::<Manifest>(fragment)
        .expect("the fragment parses")
        .tables
}

/// One schema exercising every kind, every constraint, both a single and
/// a composite primary key, a foreign key and an index.
const EVERYTHING: &str = r#"
[tables.author]
primary_key = "id"

[[tables.author.fields]]
name = "id"
kind = "uuid"
required = true

[[tables.author.fields]]
name = "email"
kind = "text"
format = "email"
max_len = 254
required = true
unique = true

[tables.post]
primary_key = "id"

[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true

[[tables.post.fields]]
name = "title"
kind = "text"
min_len = 1
max_len = 200
required = true

[[tables.post.fields]]
name = "status"
kind = "enum"
values = ["draft", "published"]
required = true
default = "draft"

[[tables.post.fields]]
name = "read_minutes"
kind = "integer"
default = 0

[[tables.post.fields]]
name = "score"
kind = "real"
default = 1.0

[[tables.post.fields]]
name = "featured"
kind = "boolean"
required = true
default = false

[[tables.post.fields]]
name = "body"
kind = "json"

[[tables.post.fields]]
name = "created_at"
kind = "timestamp"
required = true
indexed = true

[[tables.post.fields]]
name = "author_id"
kind = "uuid"
indexed = true

[[tables.post.foreign_keys]]
field = "author_id"
references = "author"

[tables.tag]
primary_key = ["post_id", "label"]

[[tables.tag.fields]]
name = "post_id"
kind = "uuid"
required = true

[[tables.tag.fields]]
name = "label"
kind = "text"
required = true

[[tables.tag.foreign_keys]]
field = "post_id"
references = "post"
"#;

const SQLITE_EXPECTED: &str = "\
-- Generated by cratefield-tables from the venture manifest.
-- Dialect: sqlite. Forward-only: this file only creates.

CREATE TABLE IF NOT EXISTS author (
    id TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post (
    id TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    read_minutes INTEGER DEFAULT 0,
    score REAL DEFAULT 1.0,
    featured INTEGER NOT NULL DEFAULT 0,
    body TEXT,
    created_at TEXT NOT NULL,
    author_id TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES author (id)
);
CREATE INDEX IF NOT EXISTS post_created_at_idx ON post (created_at);
CREATE INDEX IF NOT EXISTS post_author_id_idx ON post (author_id);

CREATE TABLE IF NOT EXISTS tag (
    post_id TEXT NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY (post_id, label),
    FOREIGN KEY (post_id) REFERENCES post (id)
);
";

const POSTGRES_EXPECTED: &str = "\
-- Generated by cratefield-tables from the venture manifest.
-- Dialect: postgres. Forward-only: this file only creates.

CREATE TABLE IF NOT EXISTS author (
    id TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post (
    id TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    read_minutes BIGINT DEFAULT 0,
    score DOUBLE PRECISION DEFAULT 1.0,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    body TEXT,
    created_at TEXT NOT NULL,
    author_id TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES author (id)
);
CREATE INDEX IF NOT EXISTS post_created_at_idx ON post (created_at);
CREATE INDEX IF NOT EXISTS post_author_id_idx ON post (author_id);

CREATE TABLE IF NOT EXISTS tag (
    post_id TEXT NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY (post_id, label),
    FOREIGN KEY (post_id) REFERENCES post (id)
);
";

#[test]
fn sqlite_ddl_is_exactly_this() {
    let sql = schema(EVERYTHING).ddl(SqlDialect::Sqlite).expect("renders");
    assert_eq!(sql, SQLITE_EXPECTED);
}

#[test]
fn postgres_ddl_is_exactly_this() {
    let sql = schema(EVERYTHING)
        .ddl(SqlDialect::Postgres)
        .expect("renders");
    assert_eq!(sql, POSTGRES_EXPECTED);
}

#[test]
fn the_same_definition_always_renders_byte_identical_sql() {
    // Twice from one value, and once more from a second parse of the same
    // manifest, which is what would catch an iteration order that depends
    // on a hash map rather than on the declaration.
    for dialect in SqlDialect::ALL.iter().copied() {
        let once = schema(EVERYTHING).ddl(dialect).expect("renders");
        let twice = schema(EVERYTHING).ddl(dialect).expect("renders");
        let reparsed = schema(EVERYTHING).ddl(dialect).expect("renders");
        assert_eq!(once.as_bytes(), twice.as_bytes());
        assert_eq!(once.as_bytes(), reparsed.as_bytes());
    }
}

#[test]
fn the_manifests_section_order_does_not_reach_the_sql() {
    let declared = schema(EVERYTHING);
    let mut shuffled = declared.clone();
    shuffled.tables.reverse();
    // `Schema::new` is what a caller uses to build a schema by hand, and
    // it sorts, so a reversed input renders the same script.
    let sorted = Schema::new(shuffled.tables);
    assert_eq!(
        sorted.ddl(SqlDialect::Sqlite).expect("renders"),
        declared.ddl(SqlDialect::Sqlite).expect("renders")
    );
}

#[test]
fn both_dialects_pass_the_portable_sql_lint() {
    // The same predicate `fz doctor` runs over a module's migrations and
    // the Postgres runner uses to pick a migration set.
    for dialect in SqlDialect::ALL.iter().copied() {
        let sql = schema(EVERYTHING).ddl(dialect).expect("renders");
        let hits = cratefield_core::lint_portable_sql(&sql);
        assert!(hits.is_empty(), "{}: {hits:?}", dialect.name());
    }
}

#[test]
fn generated_ddl_only_creates() {
    for dialect in SqlDialect::ALL.iter().copied() {
        let sql = schema(EVERYTHING)
            .ddl(dialect)
            .expect("renders")
            .to_uppercase();
        // The three absences below are all satisfied by an empty string,
        // so prove there is SQL to be forward-only about first.
        assert!(
            sql.contains("CREATE TABLE"),
            "{dialect:?} rendered no table: {sql}"
        );
        assert!(!sql.contains("DROP "), "forward-only: no DROP");
        assert!(!sql.contains("ALTER "), "forward-only: no ALTER");
        assert!(!sql.contains("DELETE "), "forward-only: no DELETE");
    }
}

#[test]
fn an_invalid_definition_renders_no_sql() {
    let schema = schema(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.post.fields]]
name = "order"
kind = "text"
"#,
    );
    let error = schema
        .ddl(SqlDialect::Sqlite)
        .expect_err("a reserved word must not reach SQL");
    assert!(
        error.problems.iter().any(|line| line.contains("reserved")),
        "{:#?}",
        error.problems
    );
}

#[test]
fn a_quote_in_a_literal_is_doubled() {
    let sql = schema(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.post.fields]]
name = "note"
kind = "text"
default = "it's here"
[[tables.post.fields]]
name = "state"
kind = "enum"
values = ["it's on", "off"]
"#,
    )
    .ddl(SqlDialect::Sqlite)
    .expect("renders");
    assert!(sql.contains("DEFAULT 'it''s here'"), "{sql}");
    assert!(sql.contains("IN ('it''s on', 'off')"), "{sql}");
}

#[test]
fn a_unique_or_primary_key_field_gets_no_second_index() {
    let sql = schema(
        r#"
[tables.post]
primary_key = "id"
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
indexed = true
[[tables.post.fields]]
name = "slug"
kind = "text"
unique = true
indexed = true
[[tables.post.fields]]
name = "author_id"
kind = "uuid"
indexed = true
"#,
    )
    .ddl(SqlDialect::Sqlite)
    .expect("renders");
    assert_eq!(sql.matches("CREATE INDEX").count(), 1, "{sql}");
    assert!(sql.contains("post_author_id_idx"), "{sql}");
}

#[test]
fn an_index_name_longer_than_an_identifier_is_rejected() {
    let long = "a".repeat(60);
    let fragment = format!(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.post.fields]]
name = "{long}"
kind = "text"
indexed = true
"#
    );
    let error = schema(&fragment)
        .ddl(SqlDialect::Sqlite)
        .expect_err("post_<60 chars>_idx is 69 characters");
    assert!(
        error
            .problems
            .iter()
            .any(|line| line.contains("generated index name")),
        "{:#?}",
        error.problems
    );
}

#[test]
fn a_referenced_table_is_created_first_even_when_its_name_sorts_later() {
    // Name order puts `line_item` before `product`, and Postgres then
    // answers `relation "product" does not exist` and creates nothing.
    let sql = schema(
        r#"
[tables.line_item]
primary_key = "id"
[[tables.line_item.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.line_item.fields]]
name = "product_id"
kind = "uuid"
[[tables.line_item.foreign_keys]]
field = "product_id"
references = "product"

[tables.product]
primary_key = "id"
[[tables.product.fields]]
name = "id"
kind = "uuid"
required = true
"#,
    )
    .ddl(SqlDialect::Postgres)
    .expect("renders");

    let product = sql
        .find("CREATE TABLE IF NOT EXISTS product")
        .expect("product");
    let line_item = sql
        .find("CREATE TABLE IF NOT EXISTS line_item")
        .expect("line_item");
    assert!(product < line_item, "{sql}");
}

#[test]
fn creation_order_is_the_smallest_one_that_works_and_is_stable() {
    // Only `line_item` has to move, so `alpha` and `zulu` stay in name
    // order around it and two renderings are byte-identical.
    let fragment = r#"
[tables.alpha]
primary_key = "id"
[[tables.alpha.fields]]
name = "id"
kind = "uuid"
required = true

[tables.line_item]
primary_key = "id"
[[tables.line_item.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.line_item.fields]]
name = "product_id"
kind = "uuid"
[[tables.line_item.foreign_keys]]
field = "product_id"
references = "product"

[tables.product]
primary_key = "id"
[[tables.product.fields]]
name = "id"
kind = "uuid"
required = true

[tables.zulu]
primary_key = "id"
[[tables.zulu.fields]]
name = "id"
kind = "uuid"
required = true
"#;
    let sql = schema(fragment).ddl(SqlDialect::Sqlite).expect("renders");
    let order: Vec<&str> = sql
        .lines()
        .filter_map(|line| line.strip_prefix("CREATE TABLE IF NOT EXISTS "))
        .map(|rest| rest.trim_end_matches(" ("))
        .collect();
    assert_eq!(order, ["alpha", "product", "line_item", "zulu"], "{sql}");

    let again = schema(fragment).ddl(SqlDialect::Sqlite).expect("renders");
    assert_eq!(sql.as_bytes(), again.as_bytes());
}

#[test]
fn a_reference_cycle_renders_no_sql() {
    let error = schema(
        r#"
[tables.author]
primary_key = "id"
[[tables.author.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.author.fields]]
name = "post_id"
kind = "uuid"
[[tables.author.foreign_keys]]
field = "post_id"
references = "post"

[tables.post]
primary_key = "id"
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.post.fields]]
name = "author_id"
kind = "uuid"
[[tables.post.foreign_keys]]
field = "author_id"
references = "author"
"#,
    )
    .ddl(SqlDialect::Postgres)
    .expect_err("a cycle has no creation order");
    assert!(
        error
            .problems
            .iter()
            .any(|line| line.contains("reference cycle")),
        "{:#?}",
        error.problems
    );
}

#[test]
fn a_not_null_primary_key_is_required_by_the_validator_and_the_view_too() {
    // Finding 5: `column_sql` writes NOT NULL for a primary key, so a
    // primary key the row validator or the JSON Schema treated as
    // optional would be a 500 where a 400 was correct.
    let schema = schema(EVERYTHING);
    let sql = schema.ddl(SqlDialect::Sqlite).expect("renders");
    for table in &schema.tables {
        for key in &table.primary_key {
            let field = table.field(key).expect("the primary key is declared");
            let column = sql
                .lines()
                .find(|line| line.trim_start().starts_with(&format!("{key} ")))
                .expect("the column is rendered");
            assert!(column.contains("NOT NULL"), "{column}");
            assert!(!column.contains("DEFAULT"), "{column}");
            assert!(field.default.is_none(), "the fixture has no default here");

            let errors = validate_row(table, &json!({})).expect_err("an empty row is rejected");
            assert!(
                errors
                    .errors()
                    .iter()
                    .any(|error| error.field == *key && error.code == ErrorCode::Required),
                "{key} is NOT NULL but the validator accepted its absence: {errors}"
            );

            let view = json_schema(table);
            assert!(
                view["required"]
                    .as_array()
                    .expect("required is a list")
                    .iter()
                    .any(|name| name == key.as_str()),
                "{key} is NOT NULL but the JSON Schema does not require it"
            );
        }
    }
}

#[test]
fn an_integral_default_written_as_a_decimal_renders_as_an_integer() {
    let sql = schema(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.post.fields]]
name = "views"
kind = "integer"
default = 42.0
"#,
    )
    .ddl(SqlDialect::Sqlite)
    .expect("renders");
    assert!(sql.contains("views INTEGER DEFAULT 42"), "{sql}");
}

#[test]
fn a_control_character_in_an_enum_member_renders_no_sql() {
    // The renderer only doubles quotes, so a control character went
    // through raw: a NUL truncates the statement in SQLite and PostgreSQL
    // refuses it outright, and either way the schema file is not what the
    // declaration said. Escaping would preserve a member no caller wants,
    // so the declaration is refused instead.
    // The member is written as a TOML escape, so this source file stays
    // printable and the parser is what produces the control character.
    for (member, what) in [
        (r"two\nlines", "newline"),
        (r"nul\u0000here", "NUL"),
        (r"bell\u0007here", "BEL"),
    ] {
        let fragment = format!(
            r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.post.fields]]
name = "state"
kind = "enum"
values = ["ok", "{member}"]
"#
        );
        let schema = schema(&fragment);
        let error = schema
            .ddl(SqlDialect::Sqlite)
            .expect_err("a {what} must not reach SQL");
        assert!(
            error
                .problems
                .iter()
                .any(|line| line.contains("control character")),
            "{what}: {:#?}",
            error.problems
        );
        // And the message is printable: the offending character cannot be
        // the thing that makes the error unreadable.
        assert!(
            error
                .problems
                .iter()
                .all(|line| !line.chars().any(char::is_control)),
            "{what}: the refusal echoed the control character back"
        );
    }
}

#[test]
fn an_integer_default_outside_i64_renders_no_sql() {
    // `literal()` falls back to a quoted string for an integer it cannot
    // render, which would put `'9223372036854775809'` in an INTEGER
    // column. The declaration check is what stops it getting that far.
    let schema = schema(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true
[[tables.post.fields]]
name = "count"
kind = "integer"
default = 9223372036854775808
"#,
    );
    let error = schema
        .ddl(SqlDialect::Sqlite)
        .expect_err("an out-of-range default must not reach SQL");
    assert!(
        error.problems.iter().any(|line| line.contains("64 bits")),
        "{:#?}",
        error.problems
    );
}
